question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "Coca-Cola's original colour was green.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "There are 86400 seconds in a day.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "The word 'news' originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "The term 'Spam'; came before the food product 'Spam'.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "Sitting for more than three hours a day can cut two years off a person's life expectancy.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "Albert Einstein had trouble with mathematics when he was in school.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "The scientific name for the Southern Lights is Aurora Australis?",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "The commercial UK channel ITV stands for 'International Television'.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.' is a grammatically correct sentence.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
      "correct_answer": "True", "incorrect_answers": ["False"]}
]

# question_data = [
#     {"category": "Science: Computers",
#      "type": "boolean",
#      "difficulty": "easy",
#      "question": "Linus Torvalds created Linux and Git.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "The programming language 'Python'; is based off a modified version of 'JavaScript'.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "'HTML' stands for Hypertext Markup Language.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "The Windows 7 operating system has six main editions.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "The Windows ME operating system was released in the year 2000.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "The Python programming language gets its name from the British comedy group 'Monty Python.'",
#      "correct_answer": "True", "incorrect_answers": ["False"]}
# ]

# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to"
#              " eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state "
#              "funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"}
# ]
